version: "3.9"  # optional since v1.27.0
services:
  mongo:
    image: mongo:4.2.5
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: HHPebl16917
  redis:
    image: redis:6.2.6
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cmsadmin
      POSTGRES_PASSWORD: GXNbnl48430
      PGDATA: /data/db/postgres